version: "3.8"

volumes:
  userapp:
  productapp:
  orderapp:
  frontendapp:

services:
  user-service:
    container_name: user-service-c
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    volumes:
      - userapp:/userapp
    restart: always

  product-service:
    container_name: product-service-c
    build:
      context: ./product-service
    ports:
      - "5002:5002"
    volumes:
      - productapp:/productapp
    restart: always

  order-service:
    container_name: order-service-c
    build:
      context: ./order-service
    ports:
      - "5003:5003"
    volumes:
      - orderapp:/orderapp
    restart: always

  frontend-service:
    container_name: frontend-service-c
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - frontendapp:/frontendapp
    restart: always

