apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: allergysnip/user-service:latest
          ports:
            - containerPort: 5001
          volumeMounts:
            - mountPath: /userapp
              name: userapp-volume
      volumes:
        - name: userapp-volume
          persistentVolumeClaim:
            claimName: userapp-pvc
